"""added connections

Revision ID: c2a5ff589988
Revises: c9163e24be10
Create Date: 2020-01-02 21:56:54.179383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2a5ff589988'
down_revision = 'c9163e24be10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connections',
    sa.Column('user_a_id', sa.Integer(), nullable=True),
    sa.Column('user_b_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_a_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_b_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connections')
    # ### end Alembic commands ###
