"""added interests

Revision ID: c4e7f20910c0
Revises: 2790c45c03b7
Create Date: 2020-01-25 15:42:23.544397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4e7f20910c0'
down_revision = '2790c45c03b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('interests', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('skills_to_build', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'skills_to_build')
    op.drop_column('user', 'interests')
    # ### end Alembic commands ###
