"""new fields in model

Revision ID: c9163e24be10
Revises: 8300c29bb546
Create Date: 2020-01-02 21:20:41.026726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9163e24be10'
down_revision = '8300c29bb546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=150), nullable=True))
    op.add_column('user', sa.Column('major', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('name', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('year', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'year')
    op.drop_column('user', 'name')
    op.drop_column('user', 'major')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
